include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Code quality
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    unnecessary_null_checks: true
    prefer_single_quotes: true
    unawaited_futures: true
    no_duplicate_case_values: true
    prefer_const_literals_to_create_immutables: true
    sort_child_properties_last: true
    use_super_parameters: true

    # Reliability
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    control_flow_in_finally: true
    empty_statements: true
    throw_in_finally: true

analyzer:
  errors:
    invalid_annotation_target: ignore
